# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b11cd7274eb42d9d2c689baf207468cb67c8d9e8cb665cb9b65e7569c02782ae36cdd150670837253993f86d7ea9789392251e0a8a447e67f8877ecc96d1343

test:
  secret_key_base: 4107af7ec384c5bba96ec707903ba4cae5dd7fc694e325477d3d6dfc786de61d33d522fec300b451a5b6a25b22bce9d0af2deb944478d35e39ff975469ff11f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
